### ISSUE TITLE
Base de donnée pour stocker les informations si le bot crash ou doit redémarrer.

### ISSUE THREAD

**Issue by theorzr** [LesBidouilles/bot-discord#9]
Il faudrait mettre en place une DB pour stocker par exemple 
- [ ] le message qui serait utilisé pour la définition de grade par les réactions (#7)
- [ ] les channels temporaires (#1)
- [ ] le rôle de modération (#6)
- [ ] le canal de log (#5)
- [ ] l'horaire de fin des sanctions (#6)
    - [ ] tempmutes
    - [ ] tempban
- [ ] les commandes simples (#8)
- [ ] les statistiques (#2)

**Comment by nils-van-zuijlen** [comment]
Quel SGBDR utiliser ?
SQLite n'est pas envisageable, il ne permet pas les accès concurrents.

**Comment by theorzr** [comment]
Perso j'aurais dis celui que je sais le mieux utilisé, c'est a dire MySQL mais il est de moins en moins côté j'ai l'impression, donc a vous de voir je ne m'y connait pas à font dans ce domaine.

**Comment by nils-van-zuijlen** [comment]
MySQL a tendance à être remplacé par MongoDB, qui a un fonctionnement semblable (je crois, enfin, c'est du SQL, donc...)

**Comment by iooner** [comment]
postgresql :)

**Comment by theorzr** [comment]
Ok merci je ne connaissais pas, ça à l'air bien sympa postegre
